### ISSUE TITLE
Distinct monster entity declarations for map editor

### ISSUE THREAD

**Issue by maikmerten** [OldTimes-Software/KatanaEngine#112]
If each monster type had its own entity declaration the map editor could display the correct model and bounding box.

This could be done by having a slim spawnfunc wrapper that calls the unified model spawn code, so does not necessitate an architectural change to the monster code.

**Comment by hogsy** [comment]
Currently the code works in the reverse; you have a global system that then calls the specific spawn function for that entity using a global type list (hence the use of the style variable).

Since it's inconvenient, I'll look into an alternative implementation. It wouldn't take long as there's obviously only three monsters that will need updating for now :)
